# Generated by Django 6.0.3 on 2026-03-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalPartyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('acronym', models.CharField(max_length=20)),
                ('party_type', models.CharField(max_length=20)),
                ('ideology', models.TextField()),
                ('legal_representative', models.CharField(max_length=255)),
                ('representative_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('foundation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
