# Generated by Django 6.0.3 on 2026-03-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BancadaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_miembro', models.IntegerField(db_index=True)),
                ('id_partido', models.IntegerField(db_index=True)),
                ('tipo_curul', models.CharField(choices=[('Ordinaria', 'ORDINARIA'), ('Estatuto de Oposición', 'ESTATUTO_OPOSICION'), ('Reemplazo', 'REEMPLAZO')], default='Ordinaria', max_length=50)),
                ('fin_periodo', models.DateField()),
                ('declaraciones_bienes', models.TextField(blank=True, default='')),
                ('antecedentes_siri_sirus', models.TextField(blank=True, default='Sin antecedentes', verbose_name='Antecedentes SIRI/SIRHUS')),
                ('comision_permanente', models.CharField(choices=[('Comisión de Presupuesto', 'PRESUPUESTO'), ('Comisión de Plan de Desarrollo', 'PLAN_DESARROLLO'), ('Comisión de Gobierno', 'GOBIERNO'), ('Comisión de Hacienda', 'HACIENDA'), ('Comisión de Educación', 'EDUCACION'), ('Comisión de Salud', 'SALUD'), ('Comisión de Infraestructura', 'INFRAESTRUCTURA'), ('Comisión de Agricultura', 'AGRICULTURA'), ('Comisión de Ambiente', 'AMBIENTE'), ('Comisión de Participación Ciudadana', 'PARTICIPACION')], default='Comisión de Gobierno', max_length=100)),
                ('correo_institucional', models.EmailField(max_length=254)),
                ('profesion', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bancada',
                'verbose_name_plural': 'Bancadas',
                'db_table': 'bancada',
                'ordering': ['-created_at'],
            },
        ),
    ]
