# Generated by Django 6.0.3 on 2026-03-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancadamodel',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bancadamodel',
            name='id_miembro',
            field=models.UUIDField(db_index=True, help_text='UUID del miembro del consejo municipal'),
        ),
        migrations.AlterField(
            model_name='bancadamodel',
            name='id_partido',
            field=models.UUIDField(db_index=True, help_text='UUID del partido político'),
        ),
    ]
