# Generated by Django 6.0.3 on 2026-03-18 16:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancada', '0002_change_to_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancadamodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
